apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017        # The port on which the service is exposed internally
      targetPort: 27017   # The port on which MongoDB is running inside the container
      nodePort: 30017     # The port exposed on each node in the cluster (choose any available port)
  type: NodePort          # Specify NodePort to expose the service on each node

